# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

stake = Stake.create(:name =>"TEGUCIGALPA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Palmira", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Tegucigalpa", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Girasoles", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Reforma", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Reparto", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Hibueras", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Buenos Aires", :phone => "")

stake = Stake.create(:name =>"LA ESPERANZA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "La Esperanza", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "28 de Marzo", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "30 de Julio", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "El Sitio", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Santa Maria", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Santa Lucia", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Valle de Angeles", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Travesia", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Villa Olimpica", :phone => "")

stake = Stake.create(:name =>"GUAYMURAS")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Kennedy", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Guaymuras", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Honduras", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Miraflores", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "La Joya", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Maya", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Valencia", :phone => "")

stake = Stake.create(:name =>"UYUCA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Las Minas", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Uyuca", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Universidad", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Periferico", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Los Pinos", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Villa Real", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Tatumbla", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Zamorano", :phone => "")

stake = Stake.create(:name =>"DANLÍ")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Bella Vista", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Buena Esperanza", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Concepcion", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Danli", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "El Paraiso", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "La Reforma", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Los Arcos", :phone => "")

stake = Stake.create(:name =>"CHOLUTECA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Iberia", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Los Llanos", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Agua Caliente", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Nueva Esperanza", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Ciudad Nueva", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Yusguare", :phone => "")

stake = Stake.create(:name =>"PORVENIR")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Cabañas", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Centro", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Graneros", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "San Luis", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Porvenir", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Tamarindo", :phone => "")

stake = Stake.create(:name =>"MSN TEGUCIGALPA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Triunfo", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Orocuina", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Sabanagrande", :phone => "")

stake = Stake.create(:name =>"DTR MONJARÁS")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Monjarás", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Marcovia", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Buena Vista", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Guapinol", :phone => "")

Stake.create(:name =>"DTR SAN LORENZO")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "San Lorenzo", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Centro", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Langue", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Pespire", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Nacaome", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Obrera", :phone => "")

Stake.create(:name =>"DTR VALLE VERDE")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Villa de San Francisco", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Ojo de Agua", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Morocelí", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Cantarranas", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Yuscarán", :phone => "")

Stake.create(:name =>"COMAYAGÜELA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Comayaguela", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Lempira", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Tiloarque", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Pradera", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Flor del Campo", :phone => "")

Stake.create(:name =>"COUNTRY")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Country", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Las Mercedes", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Los Laureles", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Quezada", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Residencial", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Santa Fe", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "21 de Febrero", :phone => "")

Stake.create(:name =>"TONCONTIN")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Toncontín", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "La Peña", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "La Vega", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Monterrey", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Popular", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Sorzalez", :phone => "")

Stake.create(:name =>"LOARQUE")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Jardines de Toncontín", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Nuevo Loarque", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Pedregal", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Roble Oeste", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Tizatillo", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Ojojona", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Villeda", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "America", :phone => "")

Stake.create(:name =>"TOROCAGUA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Torocagua", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Carrizal", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Cerro Grande", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Ciudad España", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Jardines del Carrizal", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Las Villas", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Bulevard", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "San Rafael", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Villa Unión", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Zambrano", :phone => "")

Stake.create(:name =>"COMAYAGUA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Piedras Bonitas", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Circunvalación", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Comayagua", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "El Carmen", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Siguatepeque", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Flores", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Villa de San Antonio", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "La Paz", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "San Juan", :phone => "")

Stake.create(:name =>"MSN COMAYAGÜELA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Jesus de Otoro", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Intibucá", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Márcala", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Florida", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "La Entrada", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Nueva Ocotepeque", :phone => "")

Stake.create(:name =>"DTR TALANGA")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Talanga", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Jordán", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Guaimaca", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Campamento", :phone => "")

Stake.create(:name =>"DTR CATACAMAS")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Catacamas", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Juticalpa", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Guayape", :phone => "")
Chapel.create(:stake_id => stake.id, :address => "No disponible", :name => "Belén", :phone => "")

User.create!(:email=>"nestor.bermudez@unitec.edu", :first_name => "Nestor",
	:last_name=>"Bermudez", :password => "you_wont_know_my_password",
	:password_confirmation => "you_wont_know_my_password", :phone => "Not available",
	:chapel_id =>1)

Permission.create(:name => "Crear Usuario", :description => "No description available")
Permission.create(:name => "Modificar Usuario", :description => "No description available")
Permission.create(:name => "Eliminar Usuario", :description => "No description available")
Permission.create(:name => "Ver Usuario", :description => "No description available")

Permission.create(:name => "Crear Evento", :description => "No description available")
Permission.create(:name => "Modificar Evento", :description => "No description available")
Permission.create(:name => "Eliminar Evento", :description => "No description available")
Permission.create(:name => "Ver Evento", :description => "No description available")

Permission.create(:name => "Crear Recurso", :description => "No description available")
Permission.create(:name => "Modificar Recurso", :description => "No description available")
Permission.create(:name => "Eliminar Recurso", :description => "No description available")
Permission.create(:name => "Ver Recurso", :description => "No description available")

Permission.create(:name => "Crear Tag", :description => "No description available")
Permission.create(:name => "Modificar Tag", :description => "No description available")
Permission.create(:name => "Eliminar Tag", :description => "No description available")
Permission.create(:name => "Ver Tag", :description => "No description available")

Permission.create(:name => "Crear Rol", :description => "No description available")
Permission.create(:name => "Modificar Rol", :description => "No description available")
Permission.create(:name => "Eliminar Rol", :description => "No description available")
Permission.create(:name => "Ver Rol", :description => "No description available")
Permission.create(:name => "Asignar Rol", :description => "No description available")

Permission.create(:name => "Eliminar Grupo", :description => "No description available")
Permission.create(:name => "Crear Grupo", :description => "No description available")
Permission.create(:name => "Modificar Grupo", :description => "No description available")
Permission.create(:name => "Ver Grupo", :description => "No description available")
Permission.create(:name => "Asignar Grupo", :description => "No description available")
Permission.create(:name => "Ver Telefono", :description => "No description available")

Permission.create(:name => "Ver Historia", :description => "No description available")
Permission.create(:name => "Eliminar Historia", :description => "No description available")
Permission.create(:name => "Modificar Historia", :description => "No description available")
Permission.create(:name => "Crear Historia", :description => "No description available")

Permission.create(:name => "Ver Categoria", :description => "No description available")
Permission.create(:name => "Eliminar Categoria", :description => "No description available")
Permission.create(:name => "Modificar Categoria", :description => "No description available")
Permission.create(:name => "Crear Categoria", :description => "No description available")

Permission.create(:name => "Crear Articulo", :description => "No description available")
Permission.create(:name => "Modificar Articulo", :description => "No description available")
Permission.create(:name => "Eliminar Articulo", :description => "No description available")
Permission.create(:name => "Ver Articulo", :description => "No description available")

Role.create(:name => "Administrador", :permissions => Permission.all  )

User.create!(:email=>"olorenzo@outlook.com", :first_name => "Alex",
             :last_name=>"Fernandez", :password => "Omar.123",
             :password_confirmation => "Omar.123", :phone => "Not available",
             :chapel_id =>1, :roles => [Role.first])

Group.create(:name => "Líderes de Estaca")
Group.create(:name => "Secretarios")


Tag.create(:title => "GENERAL")
Category.create(:name => "GENERAL")
TagCategorization.create(:tag_id => 1, :category_id => 1)